spring:
  application:
    name: IlpTutorial_1

  datasource:
    url: jdbc:h2:mem:dronedelivery
    #driverClassName: org.h2.Driver

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop

  h2:
    console:
      enabled: true

info:
  app:
    name: ILP REST Service
    description: Simple ILP Rest Service
    version: 0.0.1

management:
  endpoints:
    web:
      exposure:
        include: info, health, env
  info:
    env:
      enabled: true

  endpoint:
    health:
      show-details: always
      probes:
        enabled: true

server:
  port: 8080
  servlet:
    session:
      timeout: 30m



ilp:
  service:
    url: https://ilp-rest-2025-bvh6e9hschfagrgy.ukwest-01.azurewebsites.net/